### ISSUE TITLE
Does not appear to work anymore

### ISSUE THREAD

**Issue by clb92** [patrik-martinko/app-chatgpt-shortcut#2]
Currently, it just opens the blank new chat page. Nothing gets inserted into the textarea and nothing gets submitted.

**Comment by patrik-martinko** [comment]
Thanks for reporting. Yeah, they changed the rendering of app and something in the background clears the query. I'm going to investigate it & update the script.

**Comment by clb92** [comment]
Awesome

**Comment by patrik-martinko** [comment]
I updated the script and submitted to the web stores for approval (v1.0.2).

**Comment by patrik-martinko** [comment]
The update has been approved by both web stores (Chrome, Firefox).

**Comment by clb92** [comment]
I've finally had time to try it out, and it works great now. Thank you for creating this addon!

I use it together with the search/bookmark shortcut feature in Firefox (so I have a bookmark to ```https://chat.openai.com/chat?q=%s``` with shortcut keyword set to "gpt"), so I can just write ```gpt <query>``` in the address bar to ask ChatGPT something quickly (though I have to manually click the CAPTCHA checkbox still)
