### ISSUE TITLE
Not working since couple of weeks

### ISSUE THREAD

**Issue by dianadebian** [patrik-martinko/app-chatgpt-shortcut#4]
Hello,

The extension appears to not work as of couple of weeks as ChatGPT might have changed something on their end.

Can you please look into it?

Thank you

**Comment by patrik-martinko** [comment]
Yes, OpenAI made a automatic redirect from `https://chat.openai.com` to `https://chatgpt.com` so my extension doesn't have access for this new domain, but it looks like OpenAI already integrated my functionality right into the service.
